### ISSUE TITLE
Error! Invalid number of arguments passed. Usage: add <module>/<module-version> or        add -m <module>/<module-version> or        add -m <module> -v <module-version>

### ISSUE THREAD

**Issue by ayushmankumar7** [norly/elmcan#6]
I tried `sudo dkms install pwd`

Result: 
Error! Invalid number of arguments passed.
Usage: add <module>/<module-version> or
       add -m <module>/<module-version> or
       add -m <module> -v <module-version>

**Comment by ayushmankumar7** [comment]
Solved it using `sudo dkms install .`

**Comment by norly** [comment]
Thanks for the feedback. The backticks around pwd weren't rendered in GitHub's view of the readme.
I've clarified the readme in commit eaf17d8.
