### ISSUE TITLE
STN11xx/STN21xx support

### ISSUE THREAD

**Issue by testuser7** [norly/elmcan#9]
Is there a plan to add support for the extended ST command set (e.g. STM, STMA)?
Documentation: https://www.scantool.net/scantool/downloads/98/stn11xx21xx_frpm_d.pdf

**Comment by norly** [comment]
There are currently no plans for this, although it shouldn't be too difficult to add if a feature fits well within the SocketCAN stack. I did note that these chips exist, but didn't dig into their extended command set. If you think that a feature is particularly useful, please feel free to submit a patch. Do note that the driver is now upstream, so please submit it directly to the [linux-can] mailinglist, and CC me.

Please keep backwards compatibility in mind. The driver, by default, needs to operate with older adapter versions. Extended command sets could be supported via private netlink settings, but that's always a difficult topic, as seen recently with another upstream driver. Again, [socket-can] is likely the best place to discuss such a feature, as other maintainers have a bigger picture in mind.

As for STM/STMA, these seem to be "filtering monitoring" commands. I am not aware of any filters being available at the hardware driver level within the SocketCAN framework, hence why CF/CM in the original ELM327 command set aren't used either. They would be useful in making the most of the limited UART bandwidth, but SocketCAN as of today expects to receive ALL packets on a CAN bus, and to do any filtering in software on an upper layer.
